### ISSUE TITLE
Circles tool still has "login with 3bot" 

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/Threefold-Circles#12]
![image](https://user-images.githubusercontent.com/13766992/102089880-37304b00-3e36-11eb-8cf5-1361ed38547a.png)

**Comment by Hamdy** [comment]
@weynandkuijpers what should be the wording here?

**Comment by weynandkuijpers** [comment]
This is what is life on the vdc testnet setup:
![image](https://user-images.githubusercontent.com/13766992/102962852-200def00-4501-11eb-9ab7-49b01748a2ee.png)

Should be all the same - 3bot - VDC - TF Circles - all where we use the ThreeFold Connect app.
so I would say "Login via ThreeFold Connect"

**Comment by weynandkuijpers** [comment]
Still not updated: All login screens using SSO (ThreeFold Connect) should state ThreeFold Connect, not 3Bot, 3Bot connect etc.

![image](https://user-images.githubusercontent.com/13766992/106565325-10de8000-6548-11eb-889c-69598f4a2e8e.png)

**Comment by weynandkuijpers** [comment]
![image](https://user-images.githubusercontent.com/13766992/107325301-f9147800-6ac2-11eb-992b-21680c9c0880.png)

Still says login with 3bot in circles.threefold.me

**Comment by weynandkuijpers** [comment]
Nothing happened to date - what do I need to to get some attention on this? @Hamdy It's open for 2 months?

![circles](https://user-images.githubusercontent.com/13766992/107904022-20a48e00-6f64-11eb-9e07-e47a8f049f84.png)

**Comment by weynandkuijpers** [comment]
This must be the hardest thing in the world to get done:
![screenshot_20210222_085005](https://user-images.githubusercontent.com/13766992/108663891-02520b80-74eb-11eb-9f71-fc72bc3ed457.png)

this cannot be very difficult (and if it is please comment on why it presents so many challenges) if someone takes it seriously and just work on it for a few minutes.  Can we please get this over with it's more than 2.5 months!!!

**Comment by xmonader** [comment]
This is not part of 3Bot 2.5 project and not related at all to 3Bot or VDC. @sasha-astiadi 

@weynandkuijpers please reach out to @Hamdy directly on telegram

**Comment by weynandkuijpers** [comment]
okay - but it has taken too long to be looked at.

**Comment by samaradel** [comment]
UI updated @Hamdy, please check login URL

**Comment by weynandkuijpers** [comment]
Still says "login with 3bot" -> should be "login with ThreeFold Connect"
![screenshot_20210310_102236](https://user-images.githubusercontent.com/13766992/110585906-c83f6580-818a-11eb-9321-0d20483ee794.png)

**Comment by samaradel** [comment]
the image below is the current UI on staging branch 

![image](https://user-images.githubusercontent.com/11662805/111060272-44e08580-84a4-11eb-8e74-bd6a53c1c4b0.png)

**Comment by weynandkuijpers** [comment]
looks good - I am no sur ehow I can test the circles tool on devnet (production version is : https://circles.threefold.me/).

But if the image is the login screen then I am good to go and create a release from this.

**Comment by weynandkuijpers** [comment]
this is not going anywhere.  I guess people are okay with leaving the term "3bot".  Closing the issue.
