### ISSUE TITLE
Implement 3bot login on TFCircles

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/Threefold-Circles#2]
part of https://github.com/threefoldtech/home/issues/378

**Comment by Hamdy** [comment]
Blocked on @samar for fixing error message notifications when something wrong happens during login
[Backend](https://github.com/threefoldtech/Threefold-Circles/tree/staging)
[Frontend](https://github.com/threefoldtech/Threefold-Circles-front/tree/threebot-login)

**Comment by samaradel** [comment]
fixed on staging

**Comment by hossnys** [comment]
3bot login is now deployed and tested on [staging](https://staging-circles.threefold.me)
