### ISSUE TITLE
feature: Add Crisp Chat applet to staging/production

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/Threefold-Circles#4]
Get the new Crips Chat app into: circles.threefold.me and staging-circles.threefold.me
We won't have a lot of people chatting to us on staging so does not matter to implement it there as well.

html snippet that needs to go into the head:

<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="1a5a5241-91cb-4a41-8323-5ba5ec574da0";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

**Comment by PeterNashaat** [comment]
- Added to staging [Link](https://staging-circles.threefold.me/), will be migrated to production next sunday
